---
title: "Optimal Season Running Schedule"
author: 
     - "Clancy Andrews"
header-includes:
   - \usepackage{amssymb}
   - \usepackage{amsmath}
   - \usepackage{graphicx,float}
   - \usepackage{natbib}
   - \usepackage{geometry}
   - \usepackage{listings}
   - \usepackage{xcolor}
   - \usepackage{courier}
output:
  pdf_document: default
fontsize: 12pt
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\bigbreak

\center
## Executive Summary
\raggedright

|       The goal of this project is to create a fast and easy way for an individual to curate a running schedule that allows them to train for competition. There are three different types of workouts. Aerobic workouts, which improve the efficiency of the body's cardiovascular system in terms of oxygen intake and internal transportation of oxygen, involve longer runs at an easier pace. Anaerobic workouts, which improve muscle strength and speed, involve short, interval speed workouts, i.e., sprinting. Threshold workouts, which improve lactate levels in the body and prevent the onset of fatigue, involve 3 to 15 kilometer runs with an average heart rate at 80% of the individual's maximum heart rate. To determine an optimal solution to the project, our goal was to minimize summation of the differences between the total mileage ran and the goal mileage for each of the corresponding weeks in the competitive season. 

|       This project had many constraints. We had to start with allocating around 80% of the total weekly mileage to aerobic workouts, with the rest of the mileage getting split between anerobic and threshold workouts. The longest aerobic run could not exceed more than 30% of the total weekly mileage. We could not do two consecutive anerobic workouts, and no more than 3 anerobic workouts in one week. If we do a threshold workout, it has to be at most 15 kilometers. We wanted to do 3 to 6 workouts a week and only one workout a day as most individuals do not have time to do more than one workout a day. With these being some of the constraints in the project, we were able to model them and use computer software to determine an optimal solution for a seasonal running schedule.

|       We were able to determine an optimal schedule, where we can model a season schedule up to 24 kilometers as the starting mileage provided by the user. Any starting mileage provided by the user that is over 24 kilometers renders the mixed integer program infeasible with the current constraints. However, for any runner who wants to start above 20 kilometers for a season should look into a more constrained training schedule as there are constraints not present in this model that will more greatly impact their results from training. Beginners will benefit more using this program to build their training schedules. The optimal season running schedule for a starting mileage of $20 \ km$ is provided on the last page of this report. 

\break

\center
## Introduction
\raggedright


|       As a competitive runner, I wish to optimize my seasonal running schedule, allowing me to focus on training and reap the performance benefits. Being busy with work and school as a priority, I don't always have time to sit down and write up a seasonal running schedule that will allow me to have the most performance boosting results. Especially when the results of a workout are not determined until after a fortnight. Our goal is to get as close to the target weekly mileage as we can for each week in the season. This will ensure that no overtraining will occur and we can still improve moving forward with training.

\center
## Background
\raggedright

|       There are many aspects that go into planning a training schedule for a week. For this instance, the only prior information necessary for us to optimize a week of training is the previous week's total mileage. It is recommended that the total weekly mileage for the current week is only a 10% increase from the previous week's total mileage, to prevent over training and injury. We use the term mileage to indicate the total distance ran during the week, but the units for this distance is in kilometers, since most competitive races are measured using the metric system.  



|       There are three different types of workouts. Aerobic workouts, which improve the efficiency of the body's cardiovascular system in terms of oxygen intake and internal transportation of oxygen, involve longer runs at an easier pace. Anaerobic workouts, which improve muscle strength and speed, involve short, interval speed workouts, i.e., sprinting. Threshold workouts, which improve lactate levels in the body and prevent the onset of fatigue, involve 3 to 15 kilometer runs with an average heart rate at 80% of the individual's maximum heart rate.



|       It is typically advised that, of the total weekly mileage, between 60% to 80% should be done doing aerobic workouts. If this is the start of training, starting around 80% will allow an individual to develop an endurance "base". Once the base is built up, the threshold and anaerobic mileage can be increased to gain speed. The longest aerobic run of the week can only account for 30% of the total weekly mileage. Since long runs require more time to do, we want to set our longest run to be either on a Saturday or Sunday during the week. On the day after the long run, we can either do a shorter aerobic workout or have a recovery day. Threshold and anaerobic workouts should account for 10% to 20% of the weekly total mileage each. The longest threshold run of the week should only account for 10% of the total weekly mileage. At most 3 anaerobic workouts should be done during any one week and we cannot do two anaerobic workouts in a row. It is also important to train at least three times a week to see improvement and at most six times a week as to prevent injury. Only one workout of any type should be done per day.



|       A typical season in track and field or cross country is around 4 months (3 months of normal season and 1 month of nationals in high school) with professional seasons lasting longer. For the average runner, it would be better to do a 4 month training plan so a break can be taken after the 4 months to prevent over training and burnout (as this frequently can happen). It would also be beneficial to taper near the end of the season to better get ready for any big races/competitions that are scheduled. Tapering is the reduction of mileage/running intensity and allows a runner to better prepare their body for competition via additional rest, nutrition, and fine tuning of running form. To start a taper, we can reduce the current mileage by 20% of the previous week's mileage. This will occur for the last 2 weeks of the season.

\center
## Objective Variables
\raggedright

|       We can account for each workout type's total kilometers ran for each day using the decision variables $x^t_{ij}$ where $i$ corresponds to the $i$th day of the $t$th week for $i = 1,2,3,4,5,6,7$ representing Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, and Saturday, respectively; $j$ corresponds to the $j$th workout type for $j = 1,2,3$ representing aerobic, anaerobic, and threshold, respectively; $t$ corresponds to the $t$th week where $t = 1,\ldots, 16$ for each week in the four month season. It may also be necessary to add binary decision variables $y^t_{ij}$ for running a $j$th workout type on the $i$th day of the $t$th week for $i = 1,2,3,4,5,6,7$ representing Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, and Saturday, respectively, $j$ corresponding to the $j$th workout type for $j = 1,2,3$ representing aerobic, anaerobic, and threshold, respectively, and $t$ corresponding to the $t$th week where $t = 1,\ldots, 16$ for each week in the four month season. We will also have variables that are in place of constants that will be calculated after the user's input, or are dynamically determined by the stage in training. One such is $M^t$, representing the goal total mileage for week $t$. Another is $r^t_j$ representing the ratio a run can be of the total weekly mileage of week $t$ for workout type $j$. 


\center
## Objective Function
\raggedright

|       Given our objective variables above, we can formulate the objective function as follows:

$$\min \ z = \sum_{t=1}^{16}\delta^t$$

where 

$$\delta^t = \left|\sum_{i = 1}^7\sum_{j=1}^3x^t_{ij}-M^t\right|.$$ 

The goal of the objective function is to minimize the difference of the total mileage ran for week $t$ and the goal total mileage of week $t$ ($M^t$). Therefore, each week will be as close to the goal mileage as possible.


\center
## Constraints
\raggedright

|       We can model the different constraints stated in the background section using the objective variables. We can start my relating the dependent variables stated above to the independent variables. For the $\delta^t$ values, we have
$$\delta^t = \left|\sum_{i = 1}^7\sum_{j=1}^3x^t_{ij}-M^t\right|$$
which when linearized, result in the following constraints:
$$-\sum_{i = 1}^7\sum_{j=1}^3x^t_{ij}+\delta^t \le -M^t$$
and
$$-\sum_{i = 1}^7\sum_{j=1}^3x^t_{ij}-\delta^t \le -M^t.$$
These constraints allow us to relate the objective function to the difference of the total mileage ran for week $t$ and the goal total mileage of week $t$. In order for us to use $M^t$ to represent the $t$th week's goal total mileage, we must have a starting goal mileage for the season. Our current implementation gets the starting mileage in kilometers from the user before solving the linear program. In our case, our starting mileage will be $20 \ km$. We then get the following constraints:

$$
M^t = 
\begin{cases}
20 \ &\text{ if } \ t = 1 \\
\left|(1.1)M^{t-1}\right| &\text{ if }\ \forall t = 2,\ldots,14 \\
\end{cases}
$$

If $t = 15,16$, then we will change the $1.1$ value to $0.8$ to account for tapering at the end of the season. This allows us to set our current week's goal total mileage to a value as close to a 10% increase from the last weeks goal total mileage as possible and taper at the end. To use $r_j^t$ to represent the ratio a run can be of the total weekly mileage of week $t$ for workout type $j$, we have 
$$
\begin{aligned}
r^t_1 &= 0.80 \qquad \forall t = 1, \ldots , 4 \\ 
r^t_1 &= 0.75 \qquad \forall t = 5, \ldots , 8 \\
r^t_1 &= 0.70 \qquad \forall t = 9, \ldots , 12 \\
r^t_1 &= 0.65 \qquad \forall t = 13, \ldots , 14 \\
r^t_1 &= 0.60 \qquad \forall t = 15, \ldots , 16.
\end{aligned}
$$
Both anerobic and threshold workouts will have the same ratios between them, with 
$$
\begin{aligned}
r^t_j &= 0.100 \qquad \forall t = 1, \ldots , 4   \qquad \forall j = 2,3  \\ 
r^t_j &= 0.125 \qquad \forall t = 5, \ldots , 8   \qquad \forall j = 2,3   \\
r^t_j &= 0.150 \qquad \forall t = 9, \ldots , 12  \qquad \forall j = 2,3  \\
r^t_j &= 0.175 \qquad \forall t = 13, \ldots , 14 \qquad \forall j = 2,3   \\
r^t_j &= 0.200 \qquad \forall t = 15, \ldots , 16 \qquad \forall j = 2,3  .
\end{aligned}
$$
Using those ratios will allow us to update the ratio of each workout type as we gear towards more speed at the end of the season.


|       We can now construct the constraints for each running type. We can start with aerobic workouts. Our first constraint is that the total aerobic mileage per week has to be as close to $r^t_1$ percent of the total mileage for week $t$. In this case, $r^1_1 = 0.80$ and will decrease to $r^{16}_1 = 0.60$ step-wise over the 16 weeks as stated above. We get the following constraints to represent this:
$$
\begin{aligned}
-\sum_{i = 1}^7x^t_{i1}-\alpha^t &\le -(r^t_1)M^t \\
-\sum_{i = 1}^7x^t_{i1}+\alpha^t &\le -(r^t_1)M^t \\
\end{aligned}
$$
where
$$\alpha^t = \left|\sum_{i = 1}^7x^t_{i1}-(r^t_1)M^t\right|.$$
We also have the constraint where the longest aerobic run of the week cannot exceed 30% of the total weekly mileage:
$$x_{i1}^t - (0.3)M^ty^t_{i1} \le 0.$$
With these constraints, we can build an endurance base as well as strength for longer runs, further preventing injury.


|       The constraints for anerobic workouts are a bit different than for the aerobic workouts. We are only allowed to do at most 3 anerobic workouts a week. We have the following constraint to limit us to that:
$$\sum_{i=1}^7y_{i2}^t \le 3.$$
Taking the sum of anerobic runs for each day of week $t$ and restricting it to be less than or equal to 3 is how we can successfully limit the total weekly anerobic runs. We are not allowed to do two consecutive anerobic workouts, resulting in the constraint
$$y^t_{i2}+y^t_{(i+1)2} \le 1.$$
The total anerobic mileage must be around 10% of the total weekly mileage at the start of the season and will end at 20% near the end of the season. We have
$$\beta^t =\left|\sum_{i=1}^7x^t_{i2}-(r^t_2)M^t\right|$$
which results in
$$-\sum_{i=1}^7x^t_{i2}+\beta^t \le-(r^t_2)M^t$$
and
$$-\sum_{i=1}^7x^t_{i2}-\beta^t \le -(r^t_2)M^t.$$
Lastly, the longest anerobic workout session cannot be longer than 10% of the total goal weekly mileage. We have
$$x^t_{i2} - (0.1)M^ty^t_{i2} \le 0.$$
With these constraints in place, we will be able to get faster while not sacrificing our endurance base in the process.


|       For threshold workouts, we have a couple different set of constraints. First, any threshold run we do must be at most 15 kilometers long. We get the following constraint to represent this:
$$x^t_{i3} -15y^t_{i3} \le 0.$$
We also have that the total threshold mileage must be at around 10% of the total weekly mileage goal for each week $t$ and will increase to 20% by the end of the season. We then have
$$\gamma^t =\left|\sum_{i=1}^7x^t_{i3}-(r^t_3)M^t\right|$$
which results in
$$-\sum_{i=1}^7x^t_{i3}+\gamma^t \le-(r^t_3)M^t$$
and
$$-\sum_{i=1}^7x^t_{i3}-\gamma^t \le -(r^t_3)M^t.$$
Lastly, similar to the aerobic constraint for maximum distance a run can be based on weekly mileage, the longest threshold run cannot exceed 10% of the total weekly mileage. By setting the constraint where the threshold mileage for any day $i$ of week $t$ to be less than or equal to 20% of the corresponding goal weekly mileage $M^t$, we get
$$x^t_{i3} - (0.2)M^ty^t_{i3} \le 0.$$
Having these constraints will allow us to increase our tolerance to the onset of fatigue while running, and assist in our body's ability to combine our endurance and speed for competition.

|       For the rest of the constraints, we have
$$3\le\sum_{i=1}^7\sum_{j=1}^3y_{ij}^t \le 6$$
so we run at least 3 times a week and at most 6 times a week. There is also the constraint that stops us from doing more than one run a day:
$$\sum_{j=1}^3y_{ij}^t \le 1$$
for each day $i$ of each week $t$. Using the constraint presented above, when can implement the mixed integer program via software and solve to determine the result.

\center
## Results
\raggedright

|       The mixed integer program was implemented in `Python` using the `numpy` and `scipy` packages. We were able to determine an optimal schedule, where we can model a season schedule up to 24 kilometers as the starting mileage provided by the user. Any starting mileage provided by the user that is over 24 kilometers renders the mixed integer program infeasible with the current constraints. However, for any runner who wants to start above 20 kilometers for a season should look into a more constrained training schedule as there are constraints not present in this model that will more greatly impact their results from training. Beginners will benefit more using this program to build their training schedules. The optimal season running schedule for a starting mileage of $20 \ km$ is provided on the next page. For further interest in the program and for instructions on running the code for yourself, the documentation and source code can be found on the Github page [https://github.com/clancyandrews3/Optimal_Season_Running_Schedule/tree/main](https://github.com/clancyandrews3/Optimal_Season_Running_Schedule/tree/main).

\break

### Optimal Season Running Schedule ($\mathbf{20 \ km}$)

